let story = [
    { storyName: 'story-eins', soldierImg: 'level__01.jfif', chapter:'Der Anfang', story: `Es war einmal vor langer Zeit das der Ritter {PlaceHolder} durch die weiten Landen des Landes Zelda streifte. Er dachte an nicht viel außer vielleicht an den VFL. Doch dann geschah es das er eine magische Waffe fand. <br> Was machte der Held {PlaceHolder}?<br><br> A = "Waffe nehmen"<br><br> B = "Waffe weg schmeißen"<br><br> C = "Erst mal ein Nickerchen machen" `, antwortA:'Waffe nehmen', antwortB:'Waffe weg schmeißen', antwortC:'Erst mal ein Nickerchen machen', tot: 'graveyard.jpg'},

    { storyName: 'story-zwei', soldierImg: 'level__02.jfif', chapter:'Die Reise', story: `Nach dem der Held {PlaceHolder}  die Ultra heftige Waffe hatte machte er sich auf die Reiste. Die Reise war wirklich hart ;-)  Es wartete ein sehr ominöse und krasse Herausforderung auf Ihn. Was machte der Held? {Placeholder}<br><br> A = "Er nahm die Herausforderung an" <br><br> B = "Er hatte Angst und lief weg" <br><br> C = "Er machte erstmal ein Nickerchen "`, antwortA:'Er nahm die Herausforderung an', antwortB:'Er hatte Angst und lief weg', antwortC:'Erst mal ein Nickerchen machen', tot: 'graveyard.jpg'},

    { storyName: 'story-drei', soldierImg: 'level__03.jfif', chapter:'Dier Herrausvorderung', story: `Der Held stellte sich der Herausforderung und {Placeholder} erkannte das er einfach zu schwach für Aufgabe war. {PlaceHolder} nahm sich vor jeden Tag hart zu trainieren wie die Jungs seiner Borussia. <br><br> Wie trainierte unser Held? <br><br> A = "Immer heftig mit Eisen pumpen" <br><br> B = "FC Bayern beim Training zu schauen" <br><br> C ="Vielleicht ein Nickerchen  machen?"`, antwortA:'Immer heftig mit Eisen pumpen', antwortB:'FC Bayern beim Training zu schauen', antwortC:'Vielleicht ein Nickerchen machen', tot: 'graveyard.jpg'},

    { storyName: 'story-vier', soldierImg: 'level__04.jfif', chapter:'Rückschläge', story: `Nach dem unser Held {PlaceHolder} trainiert hatte wie ein Eichhörnchen auf RedBull, fühlte er die ultimative Kraft die seinen Bob Zapp artigen Körper durchströmte. Er machte sich auf die Suche nach einer entsprechenden Ausrüstung für seinen heldenhaften Körper. Was suchte unser Held? <br><br> A = "Ritterrüstung + Schild" <br><br> B = "Trikot von Borussia Dortmund"<br><br> C = "Schlafanzug"`, antwortA:'Ritterrüstung + Schild', antwortB:'Trikot von Borussia Dortmund', antwortC:'Schlafanzug', tot: 'graveyard.jpg'},

    { storyName: 'story-fuenf', soldierImg: 'level__05.jpg', chapter:'Ausrüstung', story: `Die neue Ausrüstung machte unseren Helden {Placeholder} so schnittig, das jeder Windkanal design nur so vor Neid erblasste. Nun war er gerüstet um gegen diesen mächtigen Drachen zu kämpfen. Wie gelang der Held zum Drachen? <br><br> A = "Mit einem Pferd" <br><br> B = "Nach dem Motto...der Berg kommt zum Propheten" <br><br> C = "42 - Per Anhalter"`, antwortA:'Mit einem Pferd', antwortB:'Nach dem Motto...der Berg kommt zum Propheten', antwortC:'42 - Per Anhalter', tot: 'graveyard.jpg'},

    { storyName: 'story-sechs', soldierImg: 'level__06.jfif', chapter:'Der Drache', story: `Nach einem langen ritt auf einem viel zu keinen und unbequemen Pferd, gelang der Held {PlaceHolder} zum Drachen. Der Drache ratze nur so vor sich hin. Sollte der Held {Placeholder} den Drachen wecken? <br><br> A = "Ja, natürlich" <br><br>B = "Sich zum Nickerchen daneben legen"<br><br> C = "Sich aus dem Staub machen"`, antwortA:'Ja, natürlich', antwortB:'Sich zum Nickerchen daneben legen', antwortC:'Sich aus dem Staub machen', tot: 'graveyard.jpg'},

    { storyName: 'story-sieben',soldierImg: 'level__07.jfif', chapter:'Der Kampf', story: `Unser wahrlich prächtige Held {PlaceHolder} hatte nach dem aufwecken des Drachen die Haare zu Berge stehen. Die Knie schlotterten wie ein alter r6 Diesel in einem W124. Wie konnte er den nur den Kampf gegen dieses Ungetüm gewinnen? <br><br> A = "Waffe ziehen" <br><br> B = "Löffel ziehen"<br><br> C = "Auf ein "Parlé" beharren"`, antwortA:'Waffe ziehen', antwortB:'Löffel ziehen', antwortC:'Auf ein "Parlé', tot: 'graveyard.jpg'},

    { storyName: 'story-acht', soldierImg: 'level__08.jfif', chapter:'Der Sieg', story: `Nach dem der Drache mit dem "Löffel" besiegt wurde.>> So nennt {Placeholder} seit nun das Schwert<< strömte Genugtuung und Heiterkeit seinen Body. {PlaceHolder} dachte nun Kacke, der Drache ist tot und ich kann es keinen erzählen...Also ab nach...<br><br> A = "Hause" <br><br> B ="Allianz Arena" <br><br> C = "Oktoberfest"`, antwortA:'Hause', antwortB:'Allianz Arena', antwortC:'Oktoberfest', tot: 'graveyard.jpg'},

    { storyName: 'story-neun', soldierImg: 'level__09.jfif', chapter:'Der Weg nach Hause', story: `Es bahnte sich ein sehr beschwerlicher Weg nach Hause an, so hatte er doch "leicht fertig" der Prinzessin den Kopf des Drachen versprochen. Hätte er gewusst das der Kopf fast ne Tonne wiegt hätte er sein vorlautes Maul gehalten. Aber was macht man als Held nicht alles für seine holde... ;-) <br><br> A = "Kopf mitbringen" <br><br> B = "Luis Vuitton Tasche" <br><br> C = "Eine schlaf Mütze"`, antwortA:'Kopf mitbringen', antwortB:'Luis Vuitton Tasche', antwortC:'Eine schlaf Mütze', tot: 'graveyard.jpg'},

    { storyName: 'story-zehn', soldierImg: 'highest_level.jpg', chapter:'Die schöne Prinzessin', story: `Die Prinzessin rastete förmlich aus als sie den Kopf sah. Sie war so fröhlich das sie ganz spontan ein dickes Fest für alle Anwohner der Burg veranstaltet und alle Getränke nahm sie auf Ihren Nacken! Die Bewohner feierten Sie und den Helden {PlaceHolder} bis in frühen Morgenstunden zu den fetten Beats von BustaRhymes - ENDE - `, win:'win.jfif'},

    { storyName: 'story-elf', soldierImg:'win.jfif', chapter:'ENDE', story: `ENDE`, antwortA:'', antwortB:'', antwortC:'', win:'win.jfif' }
];